# Generated by Django 5.0.4 on 2024-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi')], default='mercedes-benz', max_length=15),
        ),
    ]
