# Generated by Django 5.0.4 on 2024-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi')], max_length=15),
        ),
    ]
